# Generated by Django 6.0.2 on 2026-02-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.IntegerField(default=5),
        ),
    ]
